server:
  port: ${RTD_CSV_CONNECTOR_PORT:8080}

spring:
  application:
    name: "@project.parent.artifactId@"
    version: "@project.version@"
  batch:
    job:
      enabled: false
    initialize-schema: ${RTD_BATCH_INITIALIZE_SCHEMA:always}
  main:
    allow-bean-definition-overriding: true

info:
  build:
    artifact: "@project.parent.artifactId@"
    name: "@project.parent.artifactId@"
    description: "@project.description@"
    version: "@project.version@"


error-manager:
  enabled: true

meda:
  core:
    sessioncontext:
      enabled: false

logging:
  level:
    it.gov.pagopa.rtd.csv_connector: ${LOG_LEVEL_RTD_CSV_CONNECTOR:DEBUG}